# You can specify the intervals (wait times) between each tick of the growth task per world.
# These values are in ticks, not seconds. There is approximately 20 ticks in one real second
# so keep that in mind (IE 300 ticks = every 15 seconds).
#
# Any worlds not listed in this file will NOT HAVE A GROWTH VALUE! Keep this in mind.
#
# Simply follow the style below to add more. Keys are world names.
#
# WARNING: Setting a value too low will be too intensive for servers with many custom crops.
#          Two hundred is typically a good compromise but feel free to experiment and see
#          what works for your environment.
#
# We also support SQL (h2, sqlite, and mysql). If you specify h2 or sqlite then you do not
# need to change any additional fields, only mysql mode needs this information.
#
# WARNING: We have only tested h2 thoroughly for performance impact and therefore only
#          recommend that mode. We make no promises that sqlite or mysql will have the same
#          level of performance.
#
# Feedback:  
#    bonus-message: true/false = displays a message in the users chat when they receive a bonus drop.
#
# Jobs:
#    enabled: true/false = Enabled the Jobs Plugin Hooks for the Farming Job.
#
# ForceLoadChunks:
#    enabled: true/false = Enables the ability to force load a chunk if a Sprout is due to grow and it isn't already loaded.
#
# Updated: 2/22/2014 - Version 1.6
world:
    growth-interval: 200
sql:
    mode: h2
    host: localhost
    database: Sprout
    port: 25566
    username: minecraft
    password: minecraft
feedback:
    bonus-message: true
jobs:
    enabled: false
forceloadchunks:
    enabled: false